name: '✨ 새로운 기능'
description: '새로운 기능을 개발해 보아요~'
labels: '✨ Feature'
body:
  - type: textarea
    attributes:
      label: ✨ 개요
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세하게 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 해야 할 일
      description: 해야 할 일을 작성해 주세요.
      placeholder: |
        - [ ] 해야 할 일 1
        - [ ] 해야 할 일 2
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙏🏻 유의사항
      description: 개발시 유의해야 할 사항들을 알려주세요.
      placeholder: |
        - [ ] 유의사항 1
        - [ ] 유의사항 2
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 덧붙일 말
      description: 더 하고 싶은 말이 있다면 작성해 주세요!
